### ISSUE TITLE
WFLYCC0034: Closing leaked controller client after upgrade to 1.1.0.Alpha1

### ISSUE THREAD

**Issue by tsegismont** [wildfly/wildfly-maven-plugin#31]
I've just upgraded the Wildfly Maven Plugin version in Hawkular Metrics to make use of the new `skip` attribute in start and shutdown goals.

It works fine, except that I get this warning at the end of the build (when the goals are not skipped, of course):

```
WARN: WFLYCC0034: Closing leaked controller client
WFLYCC0030: Allocation stack trace:
at java.lang.Thread.getStackTrace(Thread.java:1552)
at org.jboss.as.controller.client.impl.RemotingModelControllerClient.<init>(RemotingModelControllerClient.java:74)
at org.jboss.as.controller.client.ModelControllerClient$Factory.create(ModelControllerClient.java:494)
at org.jboss.as.controller.client.ModelControllerClient$Factory.create(ModelControllerClient.java:200)
at org.wildfly.plugin.common.AbstractServerConnection.getClient(AbstractServerConnection.java:157)
at org.wildfly.plugin.server.StartMojo.execute(StartMojo.java:217)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

See https://travis-ci.org/hawkular/hawkular-metrics/builds/52765806#L1780

It only happens when building the whole project. It is a multi-module project and two sub-modules use the plugin for integration testing.

When only one of the sub-modules using the plugin is built, this warning does not show up.

Any idea?

**Comment by jamezp** [comment]
Yeah looks like I'm not closing the connection. It's a bug, but it shouldn't be a huge deal.

**Comment by jamezp** [comment]
Fixed as part of PR #35

**Comment by tsegismont** [comment]
Thanks for fixing issue. I'll try the changes as soon as the new version is
released.

2015-03-13 23:30 GMT+01:00 James R. Perkins <notifications@github.com>:

**Comment by tsegismont** [comment]
Hi @jamezp , do you plan to release an Alpha2 or GA? Do you know when you'll have time to do it?

**Comment by jamezp** [comment]
I'll try to do an Alpha2 this week. I want to change as much as I can before GA.

**Comment by tsegismont** [comment]
Would you mind to announce it on Wildfly dev mailing list? Or replying
here? I'll give it a try.

2015-03-23 19:18 GMT+01:00 James R. Perkins <notifications@github.com>:

**Comment by jamezp** [comment]
Alright Alpha2 has been released.

**Comment by tsegismont** [comment]
Thanks a lot! It works fine with Hawkular Metrics.
