### ISSUE TITLE
NullPointerException at DeployArtifactMojo.java:91

### ISSUE THREAD

**Issue by The-Alchemist** [wildfly/wildfly-maven-plugin#84]
Got a nice fat NPE.  Stack trace:

```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.wildfly.plugins:wildfly-maven-plugin:1.1.0.Alpha5:deploy-artifact (deploy_postgresql_driver) on project gb_services_api-functional-tests: Could not execute goal deploy-artifact on null. Reason: null
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212) ~[maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153) ~[maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145) ~[maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116) ~[maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80) ~[maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51) ~[maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128) ~[maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307) ~[maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193) ~[maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106) ~[maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863) [maven-embedder-3.3.9.jar:3.3.9]
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288) [maven-embedder-3.3.9.jar:3.3.9]
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199) [maven-embedder-3.3.9.jar:3.3.9]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289) [plexus-classworlds-2.5.2.jar:na]
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229) [plexus-classworlds-2.5.2.jar:na]
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415) [plexus-classworlds-2.5.2.jar:na]
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356) [plexus-classworlds-2.5.2.jar:na]
Caused by: org.apache.maven.plugin.MojoExecutionException: Could not execute goal deploy-artifact on null. Reason: null
	at org.wildfly.plugin.deployment.AbstractDeployment.doExecute(AbstractDeployment.java:193) ~[na:na]
	at org.wildfly.plugin.deployment.AbstractDeployment.execute(AbstractDeployment.java:137) ~[na:na]
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134) ~[maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207) ~[maven-core-3.3.9.jar:3.3.9]
	... 20 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.wildfly.plugin.deployment.DeployArtifactMojo.validate(DeployArtifactMojo.java:91) ~[na:na]
	at org.wildfly.plugin.deployment.AbstractDeployment.doExecute(AbstractDeployment.java:162) ~[na:na]
	... 23 common frames omitted
```

The full POM is at https://gist.github.com/The-Alchemist/e846dcbec2a71af779d9.

If someone points me in the right direction, I can submit a PR.

Thank you!

**Comment by mauno-h** [comment]
Code tries to resolve <classfier> tag for the dependency. Try adding adding <classfier></classifier> to your dependency.

**Comment by mauno-h** [comment]
Yep, that's the one. There is pull request for this issue: https://github.com/wildfly/wildfly-maven-plugin/pull/83

**Comment by jamezp** [comment]
My plan is to go through the pull queue this week. Hopefully time allows.

**Comment by The-Alchemist** [comment]
@jamezp : best of luck going through the PRs!

**Comment by ppalaga** [comment]
I can confirm that this issue is valid. Clearly, it is caused by the fact that `a.getClassifier()` at line 93 [1] (as of 1.1.0.Alpha5 release) can be `null`. 

[1] https://github.com/wildfly/wildfly-maven-plugin/blob/cab3e5cc39bec0fcd31801165600cbe0b41268bb/plugin/src/main/java/org/wildfly/plugin/deployment/DeployArtifactMojo.java#L93

**Comment by jamezp** [comment]
Looks like this was solved.
